// Auto-generated by scripts/add_concession_fares.js based on official DOTr/LRMC/LRTA fare matrices.
// Do not edit manually.

export const FARE_MATRIX: Record<string, Record<string, { SJT: number, BEEP: number, CONCESSION: number }>> = {
  "L1-25": {
    "L1-24": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-23": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-22": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-21": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-01": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-02": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-03": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-04": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-05": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 15
    },
    "L1-06": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-07": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-08": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-09": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-10": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-11": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-12": {
      "SJT": 40,
      "BEEP": 39,
      "CONCESSION": 20
    },
    "L1-13": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 23
    },
    "L1-14": {
      "SJT": 45,
      "BEEP": 41,
      "CONCESSION": 23
    },
    "L1-15": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 23
    },
    "L1-16": {
      "SJT": 45,
      "BEEP": 43,
      "CONCESSION": 23
    },
    "L1-17": {
      "SJT": 45,
      "BEEP": 45,
      "CONCESSION": 25
    },
    "L1-18": {
      "SJT": 50,
      "BEEP": 46,
      "CONCESSION": 25
    },
    "L1-19": {
      "SJT": 50,
      "BEEP": 49,
      "CONCESSION": 25
    },
    "L1-20": {
      "SJT": 55,
      "BEEP": 52,
      "CONCESSION": 28
    }
  },
  "L1-24": {
    "L1-25": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-23": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-22": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-21": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-01": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-02": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-03": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-04": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-05": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-06": {
      "SJT": 35,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-07": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L1-08": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-09": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-10": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 18
    },
    "L1-11": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-12": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-13": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-14": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-15": {
      "SJT": 45,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-16": {
      "SJT": 45,
      "BEEP": 41,
      "CONCESSION": 20
    },
    "L1-17": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 23
    },
    "L1-18": {
      "SJT": 45,
      "BEEP": 44,
      "CONCESSION": 23
    },
    "L1-19": {
      "SJT": 50,
      "BEEP": 47,
      "CONCESSION": 23
    },
    "L1-20": {
      "SJT": 50,
      "BEEP": 50,
      "CONCESSION": 25
    }
  },
  "L1-23": {
    "L1-25": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-24": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-22": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-21": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-01": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-02": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-03": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-04": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-05": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 13
    },
    "L1-06": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-07": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-08": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-09": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-10": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-11": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-12": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 18
    },
    "L1-13": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-14": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-15": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-16": {
      "SJT": 40,
      "BEEP": 39,
      "CONCESSION": 20
    },
    "L1-17": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-18": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 23
    },
    "L1-19": {
      "SJT": 45,
      "BEEP": 45,
      "CONCESSION": 23
    },
    "L1-20": {
      "SJT": 50,
      "BEEP": 48,
      "CONCESSION": 25
    }
  },
  "L1-22": {
    "L1-25": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-24": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-23": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-21": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-01": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-02": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-03": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-04": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-05": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-06": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-07": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-08": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-09": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 15
    },
    "L1-10": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 15
    },
    "L1-11": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-12": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-13": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-14": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 20
    },
    "L1-15": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-16": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-17": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-18": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-19": {
      "SJT": 45,
      "BEEP": 43,
      "CONCESSION": 23
    },
    "L1-20": {
      "SJT": 50,
      "BEEP": 46,
      "CONCESSION": 23
    }
  },
  "L1-21": {
    "L1-25": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-24": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-23": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-22": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-01": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-02": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-03": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-04": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-05": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-06": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-07": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-08": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-09": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-10": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 15
    },
    "L1-11": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 15
    },
    "L1-12": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-13": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-14": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-15": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 18
    },
    "L1-16": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-17": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-18": {
      "SJT": 40,
      "BEEP": 39,
      "CONCESSION": 20
    },
    "L1-19": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 20
    },
    "L1-20": {
      "SJT": 45,
      "BEEP": 45,
      "CONCESSION": 23
    }
  },
  "L1-01": {
    "L1-25": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-24": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-23": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-22": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-21": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-02": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-03": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-04": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-05": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-06": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-07": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-08": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-09": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-10": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-11": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-12": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-13": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-14": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 20
    },
    "L1-15": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 20
    },
    "L1-16": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 20
    },
    "L1-17": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 20
    },
    "L1-18": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-19": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-20": {
      "SJT": 45,
      "BEEP": 43,
      "CONCESSION": 23
    }
  },
  "L1-02": {
    "L1-25": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-24": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-23": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-22": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-21": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-01": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-03": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-04": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-05": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-06": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-07": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-08": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-09": {
      "SJT": 30,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-10": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-11": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-12": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-13": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-14": {
      "SJT": 35,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-15": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L1-16": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-17": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 20
    },
    "L1-18": {
      "SJT": 40,
      "BEEP": 34,
      "CONCESSION": 20
    },
    "L1-19": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-20": {
      "SJT": 45,
      "BEEP": 39,
      "CONCESSION": 23
    }
  },
  "L1-03": {
    "L1-25": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-24": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-23": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-22": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-21": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-01": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-02": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-04": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-05": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-06": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-07": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-08": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-09": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-10": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-11": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-12": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-13": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-14": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-15": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-16": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L1-17": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-18": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 20
    },
    "L1-19": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-20": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 20
    }
  },
  "L1-04": {
    "L1-25": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-24": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-23": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-22": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-21": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-01": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-02": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-03": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-05": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-06": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-07": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-08": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-09": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-10": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-11": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-12": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-13": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-14": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-15": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 18
    },
    "L1-16": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-17": {
      "SJT": 35,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-18": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 20
    },
    "L1-19": {
      "SJT": 40,
      "BEEP": 33,
      "CONCESSION": 20
    },
    "L1-20": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    }
  },
  "L1-05": {
    "L1-25": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 15
    },
    "L1-24": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-23": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 13
    },
    "L1-22": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-21": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-01": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-02": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-03": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-04": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-06": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-07": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-08": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-09": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-10": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-11": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-12": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-13": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-14": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-15": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-16": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 18
    },
    "L1-17": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-18": {
      "SJT": 35,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-19": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 20
    },
    "L1-20": {
      "SJT": 40,
      "BEEP": 35,
      "CONCESSION": 20
    }
  },
  "L1-06": {
    "L1-25": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-24": {
      "SJT": 35,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-23": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-22": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-21": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-01": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-02": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-03": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-04": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-05": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-07": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-08": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-09": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-10": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-11": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-12": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-13": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-14": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 15
    },
    "L1-15": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-16": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 18
    },
    "L1-17": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 18
    },
    "L1-18": {
      "SJT": 35,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-19": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 20
    },
    "L1-20": {
      "SJT": 40,
      "BEEP": 34,
      "CONCESSION": 20
    }
  },
  "L1-07": {
    "L1-25": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-24": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L1-23": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-22": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-21": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-01": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-02": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-03": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-04": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-05": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-06": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-08": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-09": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-10": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-11": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-12": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-13": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-14": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-15": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 15
    },
    "L1-16": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-17": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 18
    },
    "L1-18": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 18
    },
    "L1-19": {
      "SJT": 35,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-20": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    }
  },
  "L1-08": {
    "L1-25": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-24": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-23": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-22": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-21": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-01": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-02": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-03": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-04": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-05": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-06": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-07": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-09": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-10": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-11": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-12": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-13": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-14": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-15": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-16": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 15
    },
    "L1-17": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-18": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-19": {
      "SJT": 35,
      "BEEP": 28,
      "CONCESSION": 18
    },
    "L1-20": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    }
  },
  "L1-09": {
    "L1-25": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-24": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-23": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-22": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 15
    },
    "L1-21": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-01": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-02": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L1-03": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-04": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-05": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-06": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-07": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-08": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-10": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-11": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-12": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-13": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-14": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-15": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-16": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 15
    },
    "L1-17": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 15
    },
    "L1-18": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-19": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-20": {
      "SJT": 35,
      "BEEP": 30,
      "CONCESSION": 18
    }
  },
  "L1-10": {
    "L1-25": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-24": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 18
    },
    "L1-23": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-22": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 15
    },
    "L1-21": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 15
    },
    "L1-01": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-02": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-03": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-04": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-05": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-06": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-07": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-08": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-09": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-11": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-12": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-13": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-14": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 13
    },
    "L1-15": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-16": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 15
    },
    "L1-17": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 15
    },
    "L1-18": {
      "SJT": 30,
      "BEEP": 24,
      "CONCESSION": 15
    },
    "L1-19": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-20": {
      "SJT": 35,
      "BEEP": 29,
      "CONCESSION": 18
    }
  },
  "L1-11": {
    "L1-25": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-24": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-23": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-22": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-21": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 15
    },
    "L1-01": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-02": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-03": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-04": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-05": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-06": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-07": {
      "SJT": 20,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-08": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-09": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-10": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-12": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-13": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-14": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-15": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 13
    },
    "L1-16": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-17": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 15
    },
    "L1-18": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 15
    },
    "L1-19": {
      "SJT": 30,
      "BEEP": 24,
      "CONCESSION": 15
    },
    "L1-20": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 18
    }
  },
  "L1-12": {
    "L1-25": {
      "SJT": 40,
      "BEEP": 39,
      "CONCESSION": 20
    },
    "L1-24": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-23": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 18
    },
    "L1-22": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-21": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-01": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-02": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-03": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-04": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-05": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-06": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-07": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-08": {
      "SJT": 20,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-09": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-10": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-11": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-13": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-14": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-15": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-16": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-17": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-18": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 15
    },
    "L1-19": {
      "SJT": 30,
      "BEEP": 23,
      "CONCESSION": 15
    },
    "L1-20": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 18
    }
  },
  "L1-13": {
    "L1-25": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 23
    },
    "L1-24": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-23": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-22": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-21": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-01": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-02": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-03": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-04": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-05": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-06": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-07": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-08": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-09": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-10": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-11": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-12": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-14": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-15": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-16": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 13
    },
    "L1-17": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-18": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-19": {
      "SJT": 30,
      "BEEP": 23,
      "CONCESSION": 15
    },
    "L1-20": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    }
  },
  "L1-14": {
    "L1-25": {
      "SJT": 45,
      "BEEP": 41,
      "CONCESSION": 23
    },
    "L1-24": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-23": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-22": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 20
    },
    "L1-21": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-01": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 20
    },
    "L1-02": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L1-03": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-04": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-05": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-06": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-07": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-08": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-09": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-10": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-11": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-12": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-13": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-15": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-16": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-17": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-18": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-19": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-20": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 15
    }
  },
  "L1-15": {
    "L1-25": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 23
    },
    "L1-24": {
      "SJT": 45,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-23": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-22": {
      "SJT": 35,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-21": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 18
    },
    "L1-01": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 20
    },
    "L1-02": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-03": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-04": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-05": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-06": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-07": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-08": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-09": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-10": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-11": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-12": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-13": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-14": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-16": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-17": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-18": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 13
    },
    "L1-19": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-20": {
      "SJT": 30,
      "BEEP": 24,
      "CONCESSION": 15
    }
  },
  "L1-16": {
    "L1-25": {
      "SJT": 45,
      "BEEP": 43,
      "CONCESSION": 23
    },
    "L1-24": {
      "SJT": 45,
      "BEEP": 41,
      "CONCESSION": 20
    },
    "L1-23": {
      "SJT": 40,
      "BEEP": 39,
      "CONCESSION": 20
    },
    "L1-22": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-21": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-01": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 20
    },
    "L1-02": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-03": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L1-04": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-05": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-06": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 18
    },
    "L1-07": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-08": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-09": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 15
    },
    "L1-10": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 15
    },
    "L1-11": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-12": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-13": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-14": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-15": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L1-17": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-18": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-19": {
      "SJT": 25,
      "BEEP": 19,
      "CONCESSION": 13
    },
    "L1-20": {
      "SJT": 30,
      "BEEP": 23,
      "CONCESSION": 13
    }
  },
  "L1-17": {
    "L1-25": {
      "SJT": 45,
      "BEEP": 45,
      "CONCESSION": 25
    },
    "L1-24": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 23
    },
    "L1-23": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-22": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-21": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-01": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 20
    },
    "L1-02": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 20
    },
    "L1-03": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-04": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-05": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-06": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-07": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 18
    },
    "L1-08": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-09": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-10": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 15
    },
    "L1-11": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 15
    },
    "L1-12": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-13": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L1-14": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-15": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-16": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-18": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-19": {
      "SJT": 25,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-20": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    }
  },
  "L1-18": {
    "L1-25": {
      "SJT": 50,
      "BEEP": 46,
      "CONCESSION": 25
    },
    "L1-24": {
      "SJT": 45,
      "BEEP": 44,
      "CONCESSION": 23
    },
    "L1-23": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 23
    },
    "L1-22": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-21": {
      "SJT": 40,
      "BEEP": 39,
      "CONCESSION": 20
    },
    "L1-01": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-02": {
      "SJT": 40,
      "BEEP": 36,
      "CONCESSION": 20
    },
    "L1-03": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 20
    },
    "L1-04": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 20
    },
    "L1-05": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-06": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L1-07": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 18
    },
    "L1-08": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-09": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-10": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 15
    },
    "L1-11": {
      "SJT": 30,
      "BEEP": 24,
      "CONCESSION": 15
    },
    "L1-12": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 15
    },
    "L1-13": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-14": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L1-15": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 13
    },
    "L1-16": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L1-17": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L1-19": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L1-20": {
      "SJT": 25,
      "BEEP": 20,
      "CONCESSION": 10
    }
  },
  "L1-19": {
    "L1-25": {
      "SJT": 50,
      "BEEP": 49,
      "CONCESSION": 25
    },
    "L1-24": {
      "SJT": 50,
      "BEEP": 47,
      "CONCESSION": 23
    },
    "L1-23": {
      "SJT": 45,
      "BEEP": 45,
      "CONCESSION": 23
    },
    "L1-22": {
      "SJT": 45,
      "BEEP": 43,
      "CONCESSION": 23
    },
    "L1-21": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 20
    },
    "L1-01": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-02": {
      "SJT": 40,
      "BEEP": 39,
      "CONCESSION": 20
    },
    "L1-03": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-04": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-05": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 20
    },
    "L1-06": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 20
    },
    "L1-07": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-08": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L1-09": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 15
    },
    "L1-10": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-11": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-12": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L1-13": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-14": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-15": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-16": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L1-17": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L1-18": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L1-20": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    }
  },
  "L1-20": {
    "L1-25": {
      "SJT": 55,
      "BEEP": 52,
      "CONCESSION": 28
    },
    "L1-24": {
      "SJT": 50,
      "BEEP": 50,
      "CONCESSION": 25
    },
    "L1-23": {
      "SJT": 50,
      "BEEP": 48,
      "CONCESSION": 25
    },
    "L1-22": {
      "SJT": 50,
      "BEEP": 46,
      "CONCESSION": 23
    },
    "L1-21": {
      "SJT": 45,
      "BEEP": 45,
      "CONCESSION": 23
    },
    "L1-01": {
      "SJT": 45,
      "BEEP": 43,
      "CONCESSION": 23
    },
    "L1-02": {
      "SJT": 45,
      "BEEP": 42,
      "CONCESSION": 23
    },
    "L1-03": {
      "SJT": 40,
      "BEEP": 40,
      "CONCESSION": 20
    },
    "L1-04": {
      "SJT": 40,
      "BEEP": 39,
      "CONCESSION": 20
    },
    "L1-05": {
      "SJT": 40,
      "BEEP": 38,
      "CONCESSION": 20
    },
    "L1-06": {
      "SJT": 40,
      "BEEP": 37,
      "CONCESSION": 20
    },
    "L1-07": {
      "SJT": 35,
      "BEEP": 35,
      "CONCESSION": 18
    },
    "L1-08": {
      "SJT": 35,
      "BEEP": 34,
      "CONCESSION": 18
    },
    "L1-09": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L1-10": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L1-11": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-12": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 18
    },
    "L1-13": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L1-14": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L1-15": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L1-16": {
      "SJT": 30,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L1-17": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L1-18": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 10
    },
    "L1-19": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    }
  },
  "L2-01": {
    "L2-02": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-03": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-04": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-05": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-06": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L2-07": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-08": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L2-09": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L2-10": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L2-11": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L2-12": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L2-13": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    }
  },
  "L2-02": {
    "L2-01": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-03": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-04": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L2-05": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-06": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-07": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L2-08": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-09": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L2-10": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L2-11": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L2-12": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L2-13": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    }
  },
  "L2-03": {
    "L2-01": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-02": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-04": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-05": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-06": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-07": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-08": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L2-09": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-10": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L2-11": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L2-12": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L2-13": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 15
    }
  },
  "L2-04": {
    "L2-01": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-02": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L2-03": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-05": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-06": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-07": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L2-08": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-09": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L2-10": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-11": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L2-12": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L2-13": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    }
  },
  "L2-05": {
    "L2-01": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-02": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-03": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-04": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-06": {
      "SJT": 15,
      "BEEP": 14,
      "CONCESSION": 8
    },
    "L2-07": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-08": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L2-09": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-10": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L2-11": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-12": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L2-13": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    }
  },
  "L2-06": {
    "L2-01": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L2-02": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-03": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-04": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-05": {
      "SJT": 15,
      "BEEP": 14,
      "CONCESSION": 8
    },
    "L2-07": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-08": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-09": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-10": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-11": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L2-12": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L2-13": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    }
  },
  "L2-07": {
    "L2-01": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-02": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L2-03": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-04": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L2-05": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-06": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-08": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-09": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-10": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-11": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L2-12": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-13": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    }
  },
  "L2-08": {
    "L2-01": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L2-02": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-03": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L2-04": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-05": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L2-06": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-07": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-09": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-10": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-11": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-12": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L2-13": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    }
  },
  "L2-09": {
    "L2-01": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L2-02": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L2-03": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-04": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L2-05": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-06": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-07": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-08": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-10": {
      "SJT": 15,
      "BEEP": 14,
      "CONCESSION": 8
    },
    "L2-11": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L2-12": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-13": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    }
  },
  "L2-10": {
    "L2-01": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L2-02": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L2-03": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L2-04": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-05": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L2-06": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-07": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-08": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "L2-09": {
      "SJT": 15,
      "BEEP": 14,
      "CONCESSION": 8
    },
    "L2-11": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "L2-12": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-13": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    }
  },
  "L2-11": {
    "L2-01": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L2-02": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L2-03": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L2-04": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L2-05": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-06": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 13
    },
    "L2-07": {
      "SJT": 20,
      "BEEP": 20,
      "CONCESSION": 10
    },
    "L2-08": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-09": {
      "SJT": 20,
      "BEEP": 17,
      "CONCESSION": 10
    },
    "L2-10": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "L2-12": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-13": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    }
  },
  "L2-12": {
    "L2-01": {
      "SJT": 35,
      "BEEP": 31,
      "CONCESSION": 18
    },
    "L2-02": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L2-03": {
      "SJT": 30,
      "BEEP": 28,
      "CONCESSION": 15
    },
    "L2-04": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 15
    },
    "L2-05": {
      "SJT": 25,
      "BEEP": 24,
      "CONCESSION": 13
    },
    "L2-06": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L2-07": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-08": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L2-09": {
      "SJT": 20,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "L2-10": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-11": {
      "SJT": 15,
      "BEEP": 15,
      "CONCESSION": 8
    },
    "L2-13": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    }
  },
  "L2-13": {
    "L2-01": {
      "SJT": 35,
      "BEEP": 33,
      "CONCESSION": 18
    },
    "L2-02": {
      "SJT": 35,
      "BEEP": 32,
      "CONCESSION": 18
    },
    "L2-03": {
      "SJT": 30,
      "BEEP": 30,
      "CONCESSION": 15
    },
    "L2-04": {
      "SJT": 30,
      "BEEP": 29,
      "CONCESSION": 15
    },
    "L2-05": {
      "SJT": 30,
      "BEEP": 27,
      "CONCESSION": 15
    },
    "L2-06": {
      "SJT": 30,
      "BEEP": 26,
      "CONCESSION": 13
    },
    "L2-07": {
      "SJT": 25,
      "BEEP": 25,
      "CONCESSION": 13
    },
    "L2-08": {
      "SJT": 25,
      "BEEP": 23,
      "CONCESSION": 13
    },
    "L2-09": {
      "SJT": 25,
      "BEEP": 22,
      "CONCESSION": 13
    },
    "L2-10": {
      "SJT": 25,
      "BEEP": 21,
      "CONCESSION": 10
    },
    "L2-11": {
      "SJT": 20,
      "BEEP": 18,
      "CONCESSION": 10
    },
    "L2-12": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    }
  },
  "M3-01": {
    "M3-02": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-03": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-04": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-05": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-06": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-07": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-08": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-09": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-10": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-11": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-12": {
      "SJT": 28,
      "BEEP": 22,
      "CONCESSION": 14
    },
    "M3-13": {
      "SJT": 28,
      "BEEP": 22,
      "CONCESSION": 14
    }
  },
  "M3-02": {
    "M3-01": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-03": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-04": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-05": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-06": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-07": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-08": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-09": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-10": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-11": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-12": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-13": {
      "SJT": 28,
      "BEEP": 22,
      "CONCESSION": 14
    }
  },
  "M3-03": {
    "M3-01": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-02": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-04": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-05": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-06": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-07": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-08": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "M3-09": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-10": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-11": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "M3-12": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-13": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    }
  },
  "M3-04": {
    "M3-01": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-02": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-03": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-05": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-06": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-07": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 6
    },
    "M3-08": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-09": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "M3-10": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-11": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-12": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "M3-13": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    }
  },
  "M3-05": {
    "M3-01": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-02": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-03": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-04": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-06": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-07": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-08": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 6
    },
    "M3-09": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-10": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "M3-11": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-12": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-13": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    }
  },
  "M3-06": {
    "M3-01": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-02": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-03": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-04": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-05": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-07": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-08": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-09": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-10": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-11": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-12": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-13": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    }
  },
  "M3-07": {
    "M3-01": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-02": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-03": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-04": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 6
    },
    "M3-05": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-06": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-08": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-09": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-10": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-11": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-12": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "M3-13": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    }
  },
  "M3-08": {
    "M3-01": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-02": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-03": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "M3-04": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-05": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 6
    },
    "M3-06": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-07": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-09": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-10": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-11": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-12": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-13": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    }
  },
  "M3-09": {
    "M3-01": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-02": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-03": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-04": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "M3-05": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-06": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-07": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-08": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-10": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-11": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-12": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-13": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    }
  },
  "M3-10": {
    "M3-01": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-02": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-03": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-04": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-05": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "M3-06": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-07": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-08": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-09": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-11": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-12": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-13": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    }
  },
  "M3-11": {
    "M3-01": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-02": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-03": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "M3-04": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-05": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-06": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-07": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-08": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-09": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-10": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-12": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-13": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    }
  },
  "M3-12": {
    "M3-01": {
      "SJT": 28,
      "BEEP": 22,
      "CONCESSION": 14
    },
    "M3-02": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-03": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-04": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 10
    },
    "M3-05": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-06": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-07": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 8
    },
    "M3-08": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-09": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-10": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-11": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-13": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    }
  },
  "M3-13": {
    "M3-01": {
      "SJT": 28,
      "BEEP": 22,
      "CONCESSION": 14
    },
    "M3-02": {
      "SJT": 28,
      "BEEP": 22,
      "CONCESSION": 14
    },
    "M3-03": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-04": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-05": {
      "SJT": 24,
      "BEEP": 19,
      "CONCESSION": 12
    },
    "M3-06": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-07": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-08": {
      "SJT": 20,
      "BEEP": 16,
      "CONCESSION": 10
    },
    "M3-09": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-10": {
      "SJT": 16,
      "BEEP": 13,
      "CONCESSION": 8
    },
    "M3-11": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    },
    "M3-12": {
      "SJT": 13,
      "BEEP": 10,
      "CONCESSION": 6
    }
  },
};
